[tasks.run-create_symlinks]
description = "run tools/create_symlinks.zsh"
run = '''
zsh ./tools/create_symlinks.zsh
'''

[tasks.run-recreate-compinit]
description = "run tools/recreate_compinit.zsh"
run = '''
zsh ./tools/recreate_compinit.zsh
'''
