[tasks.run-create_symlinks]
description = "run tools/create_symlinks.zsh"
run = '''
zsh ./tools/create_symlinks.zsh
'''

[tasks.run-recreate-compinit]
description = "run tools/recreate_compinit.zsh"
run = '''
zsh ./tools/recreate_compinit.zsh
'''

[tasks.create-env]
description = "create .env from .env.1password"
run = '''
op inject -i .env.1password -o .env
'''
